### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.datasets import load_iris

### Importing the dataset

In [2]:
dataset = load_iris()

In [3]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = dataset.data

In [5]:
y = dataset.target

In [6]:
target_names = dataset.target_names

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### One Hot Encoding

In [8]:
y = tf.keras.utils.to_categorical(y)

In [9]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [11]:
y_test

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building the ANN

In [13]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 3, activation = 'softmax'))
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(X_train, y_train, batch_size = 1, epochs = 200)

Epoch 1/200
120/120 [==============================] - 1s 2ms/step - loss: 1.0066 - accuracy: 0.4750
Epoch 2/200
120/120 [==============================] - 0s 2ms/step - loss: 0.7584 - accuracy: 0.7000
Epoch 3/200
120/120 [==============================] - 0s 2ms/step - loss: 0.5953 - accuracy: 0.7583
Epoch 4/200
120/120 [==============================] - 0s 2ms/step - loss: 0.4949 - accuracy: 0.8250
Epoch 5/200
120/120 [==============================] - 0s 2ms/step - loss: 0.4314 - accuracy: 0.8333
Epoch 6/200
120/120 [==============================] - 0s 2ms/step - loss: 0.3887 - accuracy: 0.8333
Epoch 7/200
120/120 [==============================] - 0s 2ms/step - loss: 0.3610 - accuracy: 0.8500
Epoch 8/200
120/120 [==============================] - 0s 2ms/step - loss: 0.3383 - accuracy: 0.8417
Epoch 9/200
120/120 [==============================] - 0s 2ms/step - loss: 0.3214 - accuracy: 0.8667
Epoch 10/200
120/120 [==============================] - 0s 2ms/step - loss: 0.3060 - accura

In [15]:
y_pred = ann.predict(X_test)
#np.round ปัดทศนิยม
print(np.round(y_pred,3))

[[1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    1.    0.   ]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [0.    0.92  0.08 ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [0.    0.999 0.001]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [0.    0.994 0.006]
 [0.    0.98  0.02 ]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    0.984 0.016]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.999 0.001]
 [0.    0.986 0.014]
 [0.    0.395 0.605]
 [1.    0.    0.   ]
 [0.    0.001 0.999]
 [0.    1.    0.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    0.001 0.999]]


In [16]:
y_pred

array([[1.00000000e+00, 4.49831364e-18, 2.34441303e-16],
       [3.38280142e-06, 9.99988675e-01, 7.96998484e-06],
       [1.48384729e-07, 9.99710023e-01, 2.89855030e-04],
       [1.00000000e+00, 1.80805759e-18, 3.38649225e-16],
       [1.37008807e-11, 7.79957409e-05, 9.99922037e-01],
       [2.83647951e-05, 9.19714689e-01, 8.02569836e-02],
       [1.82944576e-10, 3.25255009e-04, 9.99674797e-01],
       [1.00000000e+00, 2.79016061e-17, 2.46284591e-15],
       [1.00000000e+00, 4.17254994e-16, 6.67377259e-16],
       [1.74343855e-11, 8.90711672e-05, 9.99910951e-01],
       [1.36888630e-07, 9.99357402e-01, 6.42446277e-04],
       [1.00000000e+00, 4.34179295e-17, 3.74477713e-15],
       [5.93404720e-13, 1.43096240e-05, 9.99985695e-01],
       [1.49204752e-05, 9.93817151e-01, 6.16785930e-03],
       [8.26534688e-07, 9.80486572e-01, 1.95125714e-02],
       [1.00000000e+00, 5.95815714e-19, 7.16356608e-18],
       [1.85442961e-09, 9.99972701e-01, 2.72781435e-05],
       [6.75630190e-06, 9.84017

In [17]:
ann.evaluate(X_test,y_test)

1/1 [==============================] - 0s 85ms/step - loss: 0.0358 - accuracy: 0.9667


[0.03581338748335838, 0.9666666388511658]

### Making the Confusion Matrix

In [18]:
tf.math.confusion_matrix(np.argmax(y_test, axis=1),np.argmax(y_pred, axis=1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]])>

In [20]:
data = {'Predict': target_names[np.argmax(y_pred, axis=1)], 'Actural': target_names[np.argmax(y_test, axis=1)]}
pd.DataFrame(data)

Predict     Actural
0       setosa      setosa
1   versicolor  versicolor
2   versicolor  versicolor
3       setosa      setosa
4    virginica   virginica
5   versicolor  versicolor
6    virginica   virginica
7       setosa      setosa
8       setosa      setosa
9    virginica   virginica
10  versicolor  versicolor
11      setosa      setosa
12   virginica   virginica
13  versicolor  versicolor
14  versicolor  versicolor
15      setosa      setosa
16  versicolor  versicolor
17  versicolor  versicolor
18      setosa      setosa
19      setosa      setosa
20  versicolor  versicolor
21  versicolor  versicolor
22   virginica  versicolor
23      setosa      setosa
24   virginica   virginica
25  versicolor  versicolor
26      setosa      setosa
27      setosa      setosa
28  versicolor  versicolor
29   virginica   virginica