In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
y = tf.keras.utils.to_categorical(y)
y

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [5]:
y_test

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0.

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
#เนื่องจากพอ onw hot encode แล้วได้ 5 ตัวแปร output units จึงเท่ากับ 5
ann.add(tf.keras.layers.Dense(units = 5, activation = 'softmax'))
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [8]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 200)

Epoch 1/200
16/16 [==============================] - 1s 2ms/step - loss: 1.7744 - accuracy: 0.0723
Epoch 2/200
16/16 [==============================] - 0s 2ms/step - loss: 1.6259 - accuracy: 0.1133
Epoch 3/200
16/16 [==============================] - 0s 2ms/step - loss: 1.5050 - accuracy: 0.1895
Epoch 4/200
16/16 [==============================] - 0s 2ms/step - loss: 1.4062 - accuracy: 0.2676
Epoch 5/200
16/16 [==============================] - 0s 2ms/step - loss: 1.3213 - accuracy: 0.3125
Epoch 6/200
16/16 [==============================] - 0s 2ms/step - loss: 1.2473 - accuracy: 0.3379
Epoch 7/200
16/16 [==============================] - 0s 2ms/step - loss: 1.1766 - accuracy: 0.3652
Epoch 8/200
16/16 [==============================] - 0s 2ms/step - loss: 1.1021 - accuracy: 0.4277
Epoch 9/200
16/16 [==============================] - 0s 2ms/step - loss: 0.9802 - accuracy: 0.6621
Epoch 10/200
16/16 [==============================] - 0s 2ms/step - loss: 0.8287 - accuracy: 0.8438
Epoch 11/

In [9]:
y_pred = ann.predict(X_test)
print(np.round(y_pred,3))

[[0.001 0.017 0.875 0.006 0.101]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    0.999 0.    0.001]
 [0.    0.    0.022 0.    0.978]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    0.002 0.    0.998]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    0.002 0.    0.998]
 [0.    0.    0.008 0.    0.992]
 [0.    0.    0.999 0.    0.   ]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    0.004 0.    0.996]
 [0.    0.    0.947 0.    0.053]
 [0.    0.    0.999 0.    0.001]
 [0.    0.    0.008 0.    0.992]
 [0.    0.    1.    0.    0.   ]
 [0.002 0.025 0.789 0.008 0.177]
 [0.    0.    1.    0.    0.   ]
 [0.    0.001 0.992 0.001 0.007]
 [0.    0.    0.995 0.    0.004]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    0.999 0.    0.   ]
 [0.    0.002 0.168 0.001 0.829]
 [0.    0.    0.212 0.    0.788]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    0.005 0.    0.995]
 [0.    0.001 0.259 0.    0.74 ]
 [0.    0.

In [10]:
y_test

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0.

In [11]:
ann.evaluate(X_test,y_test)

6/6 [==============================] - 0s 2ms/step - loss: 0.0425 - accuracy: 0.9942


[0.042458370327949524, 0.9941520690917969]

In [12]:
tf.math.confusion_matrix(np.argmax(y_test, axis=1),np.argmax(y_pred, axis=1))

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0, 111,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   1,   0,  59]])>

In [13]:
# np.argmax จะดูที่ตำแหน่งที่ทำให้ค่ามากสุดอย่างเช่น 0,0,1,0,0 argmax ก็จะเท่กับ 2
np.argmax(y_test, axis=1)

array([2, 2, 2, 4, 2, 4, 2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 4, 4, 4, 2, 2, 4,
       2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2,
       2, 4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2,
       4, 4, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2,
       2, 2, 2, 2, 4, 2, 4, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4,
       2, 4, 2, 4, 2, 2, 4, 2, 4, 2, 4, 4, 2, 4, 2, 2, 2], dtype=int64)

In [14]:
y_test

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0.